### PR TITLE
Angular Universal Compatibility for Server Side Rendering

### PR DESCRIPTION
**Pull request by xthilakx**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
- Conditionally mock the reference to the window object while rendering on the server side
- Removed unused import specifier tap

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: https://github.com/neroniaky/angular-token/issues/470

## What is the new behavior?
Angular Universal Compatibility for Server Side Rendering

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

I tried looking, but could not find one. 

> Tests for the changes have been added (for bug fixes / features)

Since tests run on a headless browser, I'm not sure how to mock the environment

### CODE REVIEW

**Comment by neroniaky** [comment]
@xthilakx Thanks!

**Comment by xthilakx** [comment]
Thanks for accepting my pull request!

**Comment by xthilakx** [comment]
@neroniaky @arjenbrandenburgh Would it be possible to publish a patch release on npm which includes this pull request?

**Comment by neroniaky** [comment]
@xthilakx gonna release a new version today.

**Pull request merged**
