### PR TITLE
Update Angular to v9

### PR DESCRIPTION
**Pull request by mattarau**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [X] Other... Please describe:
Framework Update (from Angular v7.x to Angular v9.x)

## What is the current behavior?

The library was not compatible with Angular 9

Issue Number: #517 

## What is the new behavior?
The library now can be installed in Angular 9 projects

## Does this PR introduce a breaking change?
[X] Yes
[ ] No

The update makes the library only compatible with Angular 9+ projects

## Other information

### CODE REVIEW

**Comment by neroniaky** [comment]
Thanks! I will take a look at it tomorrow.

**Comment by neroniaky** [comment]
Sorry for the delay. I did not forget. On it.

**Comment by bhushangahire** [comment]
Any update on this?

**Comment by charliee22** [comment]
would love to see an update on this

**Comment by bhushangahire** [comment]
@neroniaky  Any update?

**Comment by neroniaky** [comment]
Sorry again for the long wait.

**Comment by bhushangahire** [comment]
What is the version to use for this? The latest I am getting 7.0.1

**Comment by neroniaky** [comment]
@bhushangahire I published it under the next tag not latest, so you have to specify 9.0.0-beta.0 
See: https://www.npmjs.com/package/angular-token/v/9.0.0-beta.0

**Comment by bhushangahire** [comment]
Great I can see it now. Thanks, Stay Safe.

**Pull request merged**
