### PR TITLE
Gracefully handle localStorage during server-side rendering

### PR DESCRIPTION
**Pull request by xthilakx**
## PR Checklist
This PR is a continuation of my previous PR - https://github.com/neroniaky/angular-token/pull/474

Issue Number: https://github.com/neroniaky/angular-token/issues/470

## What is the new behavior?
My previous PR failed to cover localStorage, and only stubbed window object. This PR covers localStorage as well

## Does this PR introduce a breaking change?
No.

## Other information

Tested it on my project using `npm link`

### CODE REVIEW

**Comment by xthilakx** [comment]
@neroniaky @arjenbrandenburgh Could you review my PR?

**Comment by neroniaky** [comment]
@xthilakx thanks for the PR. Could you remove the package.lock. Thanks!

**Comment by xthilakx** [comment]
@neroniaky I have removed package-lock.json.

**Comment by xthilakx** [comment]
@neroniaky Thank you for merging my pull request. Could you make a patch release on npm?

**Comment by neroniaky** [comment]
@xthilakx done.

**Pull request merged**
